const display=document.getElementById("display");
document.getElementById("b1").addEventListener("click",function(){
    display.innerText="1";
});
document.getElementById("b2").addEventListener("click",function(){
    display.innerText="2";
});
document.getElementById("b3").addEventListener("click",function(){
    display.innerText="3";
});
document.getElementById("b4").addEventListener("click",function(){
    display.innerText="4";
});
document.getElementById("b5").addEventListener("click",function(){
    display.innerText="5";
});
document.getElementById("b6").addEventListener("click",function(){
    display.innerText="6";
});
document.getElementById("b7").addEventListener("click",function(){
    display.innerText="7";
});
document.getElementById("b8").addEventListener("click",function(){
    display.innerText="8";
});
document.getElementById("b9").addEventListener("click",function(){
    display.innerText="9";
});